package me.ac.ucg.kompajleri.constants;

public class TokenCodes {
    // konstante za token codes
    public static final int  // token codes
            none = 0,
            eof = 1,
            let_ = 2,
            in_ = 3,
            end_ = 4,
            if_ = 5,
            fi_ = 6,
            else_ = 7,
            while_ = 8,
            for_ = 9,
            break_ = 10,
            print_ = 11,
            then_ = 12,
            readInteger_ = 13,
            readString_ = 14,
            readBoolean_ = 15,
            readDouble_ = 16,
            identifier_ = 17,
            integer_ = 18,
            bool_ = 19,
            string_ = 20,
            double_ = 21,
            plus_ = 22,
            minus_ = 23,
            mul_ = 24,
            div_ = 25,
            mod_ = 26,
            less_ = 27,
            lessOrEqual_ = 28,
            greater_ = 29,
            greaterOrEqual_ = 30,
            assign_ = 31,
            equal_ = 32,
            notEqual_ = 33,
            and_ = 34,
            or_ = 35,
            not_ = 36,
            semicolon_ = 37,
            comma_ = 38,
            period_ = 39,
            leftParentheses_ = 40,
            rightParentheses_ = 41,
            integerConstant_ = 42,
            doubleConstant_ = 43,
            stringConstant_ = 44,
            boolConstant_ = 45,
            leftCurlyBracket_ = 46,
            rightCurlyBracket_ = 47;

}
