package me.ac.ucg.kompajleri.constants;

public class TokenNames {
    // kosntante za imena tokena
    public static final String tokenNames[] = {
            "None",
            "End of File",
            "LET",
            "IN",
            "END",
            "IF",
            "FI",
            "ELSE",
            "WHILE",
            "FOR",
            "BREAK",
            "PRINT",
            "THEN",
            "READINT",
            "READSTRING",
            "READBOOL",
            "READDOUBLE",
            "Identifier",
            "INTEGER",
            "BOOL",
            "STRING",
            "DOUBLE",
            "PLUS",
            "MINUS",
            "MULT",
            "DIV",
            "MOD",
            "Less",
            "LessOrEqual",
            "Greater",
            "GreaterOrEqual",
            "Assign",
            "Equal",
            "NotEqual",
            "And",
            "Or",
            "Not",
            "Semicolon",
            "Comma",
            "Period",
            "LeftParentheses",
            "RightParentheses",
            "IntegerConstant",
            "DoubleConstant",
            "StringConstant",
            "boolConstant",
            "LeftCurlyBracket",
            "RightCurlyBracket"
    };

}
